[package]
name = "sesamoid"
version = "0.1.0"
authors = ["Andreas Dzialocha <x12@adz.garden>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
